name: mich
description: "A Real Estate Application."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  get: ^4.6.6
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  smooth_page_indicator: ^1.0.0+2
  intl: ^0.19.0
  image_picker: ^1.0.5
  intl_phone_field: ^3.0.1
  flutter_spinkit: ^5.1.0
  flutter_otp_text_field: ^1.1.0
  pin_code_fields: ^8.0.1
  iconly: ^1.0.1
  chip_list: ^2.3.3+8
  syncfusion_flutter_sliders: ^21.2.4
  syncfusion_flutter_core: ^21.2.10
  flutter_rating_bar: ^4.0.1
  syncfusion_flutter_datepicker: ^21.2.3
  flutter_switch: ^0.3.2
  url_launcher: ^6.1.5 
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_lints: ^3.0.1
  lints: ^3.0.0
  flutter_test:
    sdk: flutter

 


flutter:
  uses-material-design: true
  assets:
    - assets/
 